#!/usr/bin/env ruby
# frozen_string_literal: true

lib = File.expand_path('../lib', __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'toggl/jobcan'

# Default action: main
%w[main version help].include?(ARGV[0]) || ARGV.unshift('main')

Toggl::Jobcan::Cli.start
