#!/usr/bin/env ruby
# frozen_string_literal: true

lib = File.expand_path('../lib', __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'toggl/jobcan'

# Default action: main
unless %w[main version].include?(ARGV[0])
  ARGV.unshift('main')
end

Toggl::Jobcan::Cli.start
